### PR TITLE
simplify code

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by ba0f3** [comment]
i think he abandoned this project, I think you should consider to take over this project

**Comment by bung87** [comment]
> i think he abandoned this project, I think you should consider to take over this project

yeah, this project is considering re-design , I contacted him in private, I also plan to create a new async mysql lib so I check this lib and found something need fix, for now make it just work is fine to me.

**Comment by ba0f3** [comment]
I used it before, but I figured out its slower than stdlib version, then I stopped using it

**Comment by bung87** [comment]
> I used it before, but I figured out its slower than stdlib version, then I stopped using it

have you got benchmark project that I can check the results ? or maybe I should wait https://github.com/itsumura-h/nim-db-benchmark

**Comment by ba0f3** [comment]
Nah I dont have benchmark yet, I just see it in action

**Pull request closed without merging**
